export enum ExceptionType {
    BAD_REQUEST = 'BAD_REQUEST',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    INVALID_TOKEN = 'INVALID_TOKEN',
    TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
    NOT_FOUND = 'NOT_FOUND',
    INVALID_FIELD = 'INVALID_FIELD',
    METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  }